#cloud-config
users:
  - name: skyeye
    groups: users
packages:
  - libopus0
  - libsoxr0
package_update: true
package_upgrade: true
write_files:
  - path: /tmp/skyeye-linux-amd64.tar.gz
    source:
      uri: https://github.com/dharmab/skyeye/releases/latest/download/skyeye-linux-amd64.tar.gz
  - path: /opt/skyeye/models/whisper.bin
    permissions: "0644"
    owner: skyeye:users
    source:
      uri: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin
  - path: /etc/skyeye/config.yaml
    permissions: "0600"
    owner: skyeye:users
    content: |
      callsign: Focus
      telemetry-address: your-tacview-address:42674
      telemetry-password: your-telemetry-password
      srs-server-address: your-srs-server:5002
      srs-eam-password: your-srs-password
      srs-frequency: 132.1
  - path: /etc/systemd/system/skyeye.service
    permissions: "0644"
    owner: root:root
    content: |
      [Unit]
      Description=SkyEye GCI Bot
      After=network-online.target

      [Service]
      Type=simple
      User=skyeye
      WorkingDirectory=/opt/skyeye
      ExecStart=/opt/skyeye/bin/skyeye --whisper-model /opt/skyeye/models/whisper.bin
      Restart=always
      RestartSec=60

      [Install]
      WantedBy=multi-user.target
runcmd:
  - tar -xzf /tmp/skyeye-linux-amd64.tar.gz -C /tmp/
  - mkdir -p /opt/skyeye/bin
  - mv /tmp/skyeye-linux-amd64/skyeye /opt/skyeye/bin/skyeye
  - chmod +x /opt/skyeye/bin/skyeye
  - chown -R skyeye:users /opt/skyeye
  - systemctl daemon-reload
  - systemctl enable skyeye
  - reboot
