package parser

// alternateRequestWords is a map of alternate forms of request words.
// These are used to provide aliases for certain commands and to deal with quality issues in speech-to-text.
var alternateRequestWords = map[string]string{
	"alphacheck":         alphaCheck,
	"alphachek":          alphaCheck,
	"arfachek":           alphaCheck,
	"buggydoke":          bogeyDope,
	"boggid":             bogeyDope,
	"pokido":             bogeyDope,
	"arfatcheck":         alphaCheck,
	"bobbiedope":         bogeyDope,
	"bobby doke":         bogeyDope,
	"bobbydo":            bogeyDope,
	"bobido":             bogeyDope,
	"boby dope":          bogeyDope,
	"bobydo":             bogeyDope,
	"bog it":             bogeyDope,
	"bogado":             bogeyDope,
	"bogeido":            bogeyDope,
	"bogeied":            bogeyDope,
	"bogey-doke":         bogeyDope,
	"bogeydoke":          bogeyDope,
	"bogeydome":          bogeyDope,
	"bogeydope":          bogeyDope,
	"bogeydote":          bogeyDope,
	"bogeydough":         bogeyDope,
	"bogeydove":          bogeyDope,
	"bogeyedope":         bogeyDope,
	"boggeto":            bogeyDope,
	"boggido":            bogeyDope,
	"boggy":              bogeyDope,
	"bogi":               bogeyDope,
	"bogido":             bogeyDope,
	"bogie":              bogeyDope,
	"bogit":              bogeyDope,
	"bogota":             bogeyDope,
	"bogue":              bogeyDope,
	"bogueed":            bogeyDope,
	"bogueto":            bogeyDope,
	"boguetto":           bogeyDope,
	"boguido":            bogeyDope,
	"bogy":               bogeyDope,
	"boido":              bogeyDope,
	"boji":               bogeyDope,
	"bokeh":              bogeyDope,
	"bokeido":            bogeyDope,
	"bokey":              bogeyDope,
	"bokeydope":          bogeyDope,
	"boki do":            bogeyDope,
	"boki":               bogeyDope,
	"booby dop":          bogeyDope,
	"boobydope":          bogeyDope,
	"boog it":            bogeyDope,
	"boogie":             bogeyDope,
	"boogiedope":         bogeyDope,
	"boogitope":          bogeyDope,
	"book it out":        bogeyDope,
	"book it up":         bogeyDope,
	"bovido":             bogeyDope,
	"bowido":             bogeyDope,
	"bowie dope":         bogeyDope,
	"boy dope":           bogeyDope,
	"bubby dope":         bogeyDope,
	"bubbydo":            bogeyDope,
	"bucket up":          bogeyDope,
	"bug it out":         bogeyDope,
	"bug it":             bogeyDope,
	"bugadobe":           bogeyDope,
	"bugadope":           bogeyDope,
	"bugged up":          bogeyDope,
	"buggetoo":           bogeyDope,
	"buggettope":         bogeyDope,
	"buggidop":           bogeyDope,
	"buggie do":          bogeyDope,
	"buggie dog":         bogeyDope,
	"buggie dope":        bogeyDope,
	"buggy co":           bogeyDope,
	"buggy do":           bogeyDope,
	"buggy dog":          bogeyDope,
	"buggy dope":         bogeyDope,
	"buggydope":          bogeyDope,
	"bugito":             bogeyDope,
	"bulgie":             bogeyDope,
	"checking in":        checkIn,
	"com check":          radioCheck,
	"comcheck":           radioCheck,
	"comes check":        radioCheck,
	"comm":               radioCheck,
	"comms":              radioCheck,
	"commscheck":         radioCheck,
	"commshack":          radioCheck,
	"comp check":         radioCheck,
	"comps check":        radioCheck,
	"coms":               radioCheck,
	"comsjack":           radioCheck,
	"declared":           declare,
	"fog it up":          bogeyDope,
	"fogey":              bogeyDope,
	"fogeyed":            bogeyDope,
	"foggy":              bogeyDope,
	"foggydope":          bogeyDope,
	"fogy dope":          bogeyDope,
	"fogy":               bogeyDope,
	"go be dope":         bogeyDope,
	"go geeto":           bogeyDope,
	"log it up":          bogeyDope,
	"lucky dope":         bogeyDope,
	"mic check":          radioCheck,
	"mike check":         radioCheck,
	"mogito":             bogeyDope,
	"odi":                bogeyDope,
	"ogi doke":           bogeyDope,
	"ogi dop":            bogeyDope,
	"ogi dope":           bogeyDope,
	"ogidope":            bogeyDope,
	"okey":               bogeyDope,
	"oogie":              bogeyDope,
	"ovido":              bogeyDope,
	"perimeter":          tripwire,
	"pogado":             bogeyDope,
	"pogadope":           bogeyDope,
	"pogdedo":            bogeyDope,
	"pogeto":             bogeyDope,
	"pogidop":            bogeyDope,
	"pogito":             bogeyDope,
	"pogy do":            bogeyDope,
	"pogy dope":          bogeyDope,
	"poke it open":       bogeyDope,
	"poke it up":         bogeyDope,
	"pokedo":             bogeyDope,
	"pokedome":           bogeyDope,
	"puggy dope":         bogeyDope,
	"radiocheck":         radioCheck,
	"radiochick":         radioCheck,
	"read a check":       radioCheck,
	"read it check":      radioCheck,
	"set threat radius":  tripwire,
	"set threat range":   tripwire,
	"set warning radius": tripwire,
	"set warning range":  tripwire,
	"set warning":        tripwire,
	"snap lock":          snaplock,
	"trip wire":          tripwire,
	"vogadope":           bogeyDope,
	"vogidobe":           bogeyDope,
	"vogue":              bogeyDope,
	"voki":               bogeyDope,
	"warn me":            tripwire,
}
