package parser

import (
	"slices"
)

// replacementLUT is a map of alternate forms of request words. These are used
// to provide aliases for certain commands and to deal with quality issues in
// speech-to-text. Do not use this variable directly, instead use replacements
// so that more specific forms are matched before more general forms.
var replacementLUT = map[string]string{
	"alphacheck":         alphaCheck,
	"alphachek":          alphaCheck,
	"alphajack":          alphaCheck,
	"alphajuck":          alphaCheck,
	"arfachek":           alphaCheck,
	"arfatcheck":         alphaCheck,
	"berkado":            bogeyDope,
	"boat be dope":       bogeyDope,
	"bobbiedope":         bogeyDope,
	"bobby doke":         bogeyDope,
	"bobby dope":         bogeyDope,
	"bobbydo":            bogeyDope,
	"bobido":             bogeyDope,
	"boby dope":          bogeyDope,
	"bobydo":             bogeyDope,
	"bog it":             bogeyDope,
	"bogado":             bogeyDope,
	"bogedop":            bogeyDope,
	"bogeido":            bogeyDope,
	"bogeied":            bogeyDope,
	"bogey-doke":         bogeyDope,
	"bogeydoke":          bogeyDope,
	"bogeydome":          bogeyDope,
	"bogeydope":          bogeyDope,
	"bogeydote":          bogeyDope,
	"bogeydough":         bogeyDope,
	"bogeydove":          bogeyDope,
	"bogeyedope":         bogeyDope,
	"bogeynope":          bogeyDope,
	"boggeto":            bogeyDope,
	"boggid":             bogeyDope,
	"boggido":            bogeyDope,
	"boggy":              bogeyDope,
	"bogi":               bogeyDope,
	"bogido":             bogeyDope,
	"bogidope":           bogeyDope,
	"bogie":              bogeyDope,
	"bogit":              bogeyDope,
	"bogota":             bogeyDope,
	"bogu":               bogeyDope,
	"bogudo":             bogeyDope,
	"bogue":              bogeyDope,
	"bogueed":            bogeyDope,
	"bogueto":            bogeyDope,
	"boguetto":           bogeyDope,
	"boguido":            bogeyDope,
	"boguie":             bogeyDope,
	"bogy":               bogeyDope,
	"boido":              bogeyDope,
	"boji":               bogeyDope,
	"bokeh":              bogeyDope,
	"bokeido":            bogeyDope,
	"bokey":              bogeyDope,
	"bokeydope":          bogeyDope,
	"boki":               bogeyDope,
	"boly dop":           bogeyDope,
	"bombdo":             bogeyDope,
	"booby dop":          bogeyDope,
	"boobydope":          bogeyDope,
	"boog it":            bogeyDope,
	"boogado":            bogeyDope,
	"boogie":             bogeyDope,
	"boogiedope":         bogeyDope,
	"boogiedote":         bogeyDope,
	"boogitope":          bogeyDope,
	"boogitup":           bogeyDope,
	"boogity":            bogeyDope,
	"book it out":        bogeyDope,
	"book it up":         bogeyDope,
	"bovido":             bogeyDope,
	"bowido":             bogeyDope,
	"bowie dope":         bogeyDope,
	"boy dope":           bogeyDope,
	"bubby dope":         bogeyDope,
	"bubbydo":            bogeyDope,
	"bucket up":          bogeyDope,
	"bug a dope":         bogeyDope,
	"bug it out":         bogeyDope,
	"bug it":             bogeyDope,
	"bugadobe":           bogeyDope,
	"bugadoop":           bogeyDope,
	"bugadope":           bogeyDope,
	"bugga":              bogeyDope,
	"bugged up":          bogeyDope,
	"bugger dope":        bogeyDope,
	"bugget":             bogeyDope,
	"buggetoo":           bogeyDope,
	"buggetto":           bogeyDope,
	"buggettope":         bogeyDope,
	"buggidop":           bogeyDope,
	"buggie":             bogeyDope,
	"buggit":             bogeyDope,
	"buggy":              bogeyDope,
	"buggydoke":          bogeyDope,
	"buggydope":          bogeyDope,
	"bugido":             bogeyDope,
	"bugidup":            bogeyDope,
	"bugidy":             bogeyDope,
	"bugito":             bogeyDope,
	"buke it up":         bogeyDope,
	"bulgie":             bogeyDope,
	"buzzy":              bogeyDope,
	"by vito":            bogeyDope,
	"checking in":        checkIn,
	"com check":          radioCheck,
	"comcheck":           radioCheck,
	"comes check":        radioCheck,
	"comm":               radioCheck,
	"comms":              radioCheck,
	"commscheck":         radioCheck,
	"commshack":          radioCheck,
	"comp check":         radioCheck,
	"comps check":        radioCheck,
	"coms":               radioCheck,
	"comsjack":           radioCheck,
	"declared":           declare,
	"doggy dope":         bogeyDope,
	"dravia check":       radioCheck,
	"fog it up":          bogeyDope,
	"fogey":              bogeyDope,
	"fogeyed":            bogeyDope,
	"foggy":              bogeyDope,
	"foggydope":          bogeyDope,
	"fogy dope":          bogeyDope,
	"fogy":               bogeyDope,
	"go be dope":         bogeyDope,
	"go geeto":           bogeyDope,
	"hogidop":            bogeyDope,
	"log it up":          bogeyDope,
	"lucky dope":         bogeyDope,
	"mic check":          radioCheck,
	"mike check":         radioCheck,
	"mogito":             bogeyDope,
	"odi":                bogeyDope,
	"ogi do":             bogeyDope,
	"ogi doke":           bogeyDope,
	"ogi dop":            bogeyDope,
	"ogi dope":           bogeyDope,
	"ogidope":            bogeyDope,
	"ogiido":             bogeyDope,
	"ogydo":              bogeyDope,
	"okey":               bogeyDope,
	"oogie":              bogeyDope,
	"ovido":              bogeyDope,
	"perimeter":          tripwire,
	"pogado":             bogeyDope,
	"pogadope":           bogeyDope,
	"pogdedo":            bogeyDope,
	"pogeto":             bogeyDope,
	"poggy dope":         bogeyDope,
	"pogido":             bogeyDope,
	"pogidop":            bogeyDope,
	"pogito":             bogeyDope,
	"pogy":               bogeyDope,
	"poke it open":       bogeyDope,
	"poke it up":         bogeyDope,
	"pokedo":             bogeyDope,
	"pokedome":           bogeyDope,
	"pokido":             bogeyDope,
	"povey":              bogeyDope,
	"pugg it up":         bogeyDope,
	"puggy dope":         bogeyDope,
	"pukido":             bogeyDope,
	"radiocheck":         radioCheck,
	"radiochick":         radioCheck,
	"radiotric":          radioCheck,
	"read a check":       radioCheck,
	"read it check":      radioCheck,
	"sent warning":       tripwire,
	"set threat radius":  tripwire,
	"set threat range":   tripwire,
	"set warning radius": tripwire,
	"set warning range":  tripwire,
	"set warning":        tripwire,
	"settrip":            tripwire,
	"snap lock":          snaplock,
	"spokie":             bogeyDope,
	"trip bar":           tripwire,
	"trip wire":          tripwire,
	"vogadope":           bogeyDope,
	"vogidobe":           bogeyDope,
	"vogue it up":        bogeyDope,
	"vogue":              bogeyDope,
	"voguy":              bogeyDope,
	"voki":               bogeyDope,
	"votigo":             bogeyDope,
	"warn me":            tripwire,
	"wogit up":           bogeyDope,
}

type replacement struct {
	Original string
	Normal   string
}

// replacements is a slice of replacment forms of request words. replacements
// is ordered so that more specific forms are matched before more general
// forms.
var replacements = []replacement{}

func init() {
	for k, v := range replacementLUT {
		replacements = append(replacements, replacement{k, v})
	}
	slices.SortFunc(replacements, func(a, b replacement) int {
		// Longer original strings should be matched first.
		if len(a.Original) > len(b.Original) {
			return -1
		}
		if len(a.Original) < len(b.Original) {
			return 1
		}
		return 0
	})
}
