run:
  build-tags:
    - nolibopusfile
linters:
  presets:
    - bugs
    - performance
    - format
  disable:
    - asciicheck  # Unicode is fine!
    - gofumpt  # Neat tool but no editor integration
    - gci  # Does some weird ordering
linters-settings:
  gosec:
    excludes:
      - G404


