name: Setup
description: Build whisper.cpp
inputs:
  whisper-cpp-repo:
    description: 'The whisper.cpp repository to use'
    required: true
    default: 'dharmab/whisper.cpp'
  whisper-cpp-version:
    description: 'The version of whisper.cpp to use'
    required: true
    default: 'v1.7.2-windows-fix'
  os:
    description: 'The operating system to build for'
    required: true
    default: 'linux'
  arch:
    description: 'The architecture to build for'
    required: true
    default: 'amd64'
  shell:
    description: 'The shell to use'
    required: true
    default: 'bash'
runs:
  using: composite
  steps:
    - name: Build whisper.cpp
      shell: ${{ inputs.shell }}
      run: make whisper
