name: Support/General Help
description: Get general help with setting up and operating SkyEye.
title: ""
labels: ["support"]
body:
  - type: textarea
    id: describe-issue
    attributes:
      label: Describe your issue
      placeholder: "Clearly and concisely state what you need help with."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log File
      description: "If you have the SkyEye logs, drag the log file into this box."
    validations:
      required: false
  - type: textarea
    id: logs-inline
    attributes:
      label: Logs
      description: "Alternatively, you can paste the log lines into this box."
      required: false
  - type: textarea
    id: acmi
    attributes:
      label: ACMI File
      description: "If you have an ACMI file, drag the file into this box."
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: input
    id: cpu
    attributes:
      label: CPU
      description: "What is the exact make and model of your CPU? e.g. Intel Core i9-13900k, AMD Ryzen 9 5900X"
    validations:
      required: true
  - type: input
    id: ram
    attributes:
      label: RAM
      description: "How much RAM do you have?"
    validations:
      required: true
  - type: input
    id: software
    attributes:
      label: Other Software
      description: "List any other software you are running on the same computer as SkyEye. e.g. DCS World client or server, SRS server, or other tools."
    validations:
      required: false
  - type: dropdown
    id: documentation
    attributes:
      label: Have you read the admin guide?
      options:
        - No, I did not read the admin guide.
        - Yes, I read the admin guide.
    validations:
      required: true
