package tags

const (
	Air             = "Air"
	Ground          = "Ground"
	Sea             = "Sea"
	Weapon          = "Weapon"
	Sensor          = "Sensor"
	Static          = "Static"
	Heavy           = "Heavy"
	Medium          = "Medium"
	Light           = "Light"
	Minor           = "Minor"
	FixedWing       = "FixedWing"
	Rotorcraft      = "Rotorcraft"
	Armor           = "Armor"
	AntiAircraft    = "AntiAircraft"
	Vehicle         = "Vehicle"
	Watercraft      = "Watercraft"
	Human           = "Human"
	Biologic        = "Biologic"
	Missile         = "Missile"
	Rocket          = "Rocket"
	Bomb            = "Bomb"
	Torpedo         = "Torpedo"
	Projectile      = "Projectile"
	Beam            = "Beam"
	Decoy           = "Decoy"
	Building        = "Building"
	Bullseye        = "Bullseye"
	Waypoint        = "Waypoint"
	Tank            = "Tank"
	Warship         = "Warship"
	AircraftCarrier = "AircraftCarrier"
	Submarine       = "Submarine"
	Infantry        = "Infantry"
	Parachutist     = "Parachutist"
	Shell           = "Shell"
	Bullet          = "Bullet"
	Grenade         = "Grenade"
	Flare           = "Flare"
	Chaff           = "Chaff"
	SmokeGrenade    = "SmokeGrenade"
	Aerodrome       = "Aerodrome"
	Container       = "Container"
	Shrapnel        = "Shrapnel"
	Explosion       = "Explosion"
)
