name: Linux
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
      - name: Test
        run: |
          go run gotest.tools/gotestsum -- -tags nolibopusfile ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
      - name: Build
        run: go build -tags nolibopusfile ./...