name: Linux
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Format
        run: go fmt ./... && git diff --exit-code
      - name: Tidy
        run: go mod tidy && git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
      - name: Test
        run: |
          go run gotest.tools/gotestsum -- -tags nolibopusfile ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
      - name: Build
        run: make skyeye
      - name: Create dist
        shell: bash
        run: |
          mkdir -p dist/linux-amd64/docs/
          cp skyeye dist/linux-amd64/skyeye.exe
          cp README.md dist/linux-amd64/README.md
          cp LICENSE dist/linux-amd64/LICENSE
          cp docs/*.md dist/linux-amd64/docs/
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: skyeye-linux-amd64
          path: dist/linux-amd64
          if-no-files-found: error
          overwrite: true