name: Windows
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: windows-latest
    env:
      CC: gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: |
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-go
            mingw-w64-x86_64-opus
            mingw-w64-x86_64-libsoxr
      - name: Build whisper.cpp
        uses: ./.github/actions/build-whisper
        with:
          os: 'windows'
          shell: 'msys2 {0}'
      - name: Build Skyeye
        shell: msys2 {0}
        run: go build -tags nolibopusfile ./...