name: Windows
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: windows-latest
    env:
      GOROOT: /ucrt64/lib/go
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: |
            base-devel
            git
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-opus
            mingw-w64-ucrt-x86_64-libsoxr
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-go
      - name: Build Skyeye
        shell: msys2 {0}
        run: make skyeye.exe
      - name: Create dist
        shell: msys2 {0}
        run: |
          mkdir -p dist/windows-amd64/docs/
          cp skyeye.exe dist/windows-amd64/skyeye.exe
          cp README.md dist/windows-amd64/README.md
          cp LICENSE dist/windows-amd64/LICENSE
          cp docs/*.md dist/windows-amd64/docs/
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: skyeye-windows-amd64
          path: dist/windows-amd64
          if-no-files-found: error
          overwrite: true
